groups:
  - name: example_alert
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          description: "{{ $labels.job }} has been down for more than 30 seconds."