  GNU nano 7.2                                                                                                                                                              docker-compose-ci.yml                                                                                                                                                                       services:
  sonarqube:
    image: sonarqube:community
    ports:
      - "9000:9000"
    networks:
      - webwizards-network
    environment:
      SONAR_JDBC_URL: "jdbc:postgresql://sonarqube-db:5432/sonar"
      SONAR_JDBC_USERNAME: "sonar"
      SONAR_JDBC_PASSWORD: "sonar"
    volumes:
      - sonarqube-data:/opt/sonarqube/data
      - sonarqube-logs:/opt/sonarqube/logs
    depends_on:
      - sonarqube-db

  sonarqube-db:
    image: postgres:13
    networks:
      - webwizards-network
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - sonarqube-db-data:/var/lib/postgresql/data

  nexus:
    image: sonatype/nexus3:latest
    ports:
      - "8081:8081"
    networks:
      - webwizards-network
    volumes:
      - nexus-data:/nexus-data
    restart: always

networks:
  webwizards-network:
    external: true

volumes:
  sonarqube-data:
  sonarqube-logs:
  sonarqube-db-data:
  nexus-data: