  GNU nano 7.2                                                                                                                      docker-compose-monitoring.yml                                                                                                                               services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert.rules.yml:/etc/prometheus/alert.rules.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - webwizards-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=gwJFMTG3yFgVxBd
    depends_on:
      - prometheus
    networks:
      - webwizards-network

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - alertmanager-data:/alertmanager
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml  # Point to your alertmanager.yml config
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    networks:
      - webwizards-network
    depends_on:
      - prometheus
networks:
  webwizards-network:
    external: true

volumes:
  prometheus-data:
  grafana-data: